"use client"
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import {RecoilRoot,} from 'recoil';
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

/*  export const metadata = {
  title: "Pavasa Travel",
  description: "Generated by create next app",
}; 
 */
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <RecoilRoot>
        
      <html lang="en">
<<<<<<< HEAD:app/layout.js
=======

>>>>>>> main:app/[locale]/layout.js
        <body className={`${inter.className} `}
suppressHydrationWarning={true}>

          <Header />
         {children}
          <Toaster position="bottom-center"/>
          <Footer />
          
        </body>
      </html>
      </RecoilRoot>
    </ClerkProvider>
  );
}
